### ISSUE TITLE
ES 6 -  error occurred while creating index

### ISSUE THREAD

**Issue by DavidFlamini** [pierky/pmacct-to-elasticsearch#9]
Hi, just leaving a quick note here, I upgraded my cluster to ES 6.2.2 yesterday and found out that the index creation function was failing to create the index with "error unknown", after a quick review of the code and ES output I fixed it by changing the content type on the http header to 'application/json'. I didn't have the time to confirm if there are any side-effects but the data seems to be flowing to ES just fine.

Here's the http function for reference.

```
# /p2es/es.py
def http(CONFIG, url, method="GET", data=None):
    auth = None
    if CONFIG['ES_AuthType'] != 'none':
        if CONFIG['ES_AuthType'] == 'basic':
            auth = HTTPBasicAuth(CONFIG['ES_UserName'], CONFIG['ES_Password'])
        elif CONFIG['ES_AuthType'] == 'digest':
            auth = HTTPDigestAuth(CONFIG['ES_UserName'], CONFIG['ES_Password'])
        else:
            raise P2ESError(
                'Unexpected authentication type: {}'.format(CONFIG['ES_AuthType'])
            )

    headers = {'Content-Type': 'application/json'} # <<<<<<<

    if method == "GET":
        return requests.get(url, auth=auth, headers=headers)
    elif method == "POST":
        return requests.post(url, auth=auth, data=data, headers=headers)
    elif method == "PUT":
        return requests.put(url, auth=auth, data=data, headers=headers)
    elif method == "HEAD":
        return requests.head(url, auth=auth, headers=headers)
    else:
        raise Exception("Method unknown: {}".format(method))
````

**Comment by pierky** [comment]
Hello @DavidFlamini, thanks for reporting this.
I fixed it in master.

I'm also adding some Docker based tests on TravisCI ("tests" branch currently); unfortunately it seems that ES staff don't want to support the `latest`tag on their Docker images (elastic/elasticsearch-docker/issues/84), otherwise it would have been easier to automate this kind of testing and to get a notification as soon as things break in case of new release.
